name: "New changes validation"

on:
    pull_request:  # yamllint disable-line rule:empty-values

permissions:
    contents: "read"
    packages: "read"

env:
    REGISTRY: "ghcr.io"
    IMAGE_NAME: "articola-tools/dockerfile-security-scanner"

jobs:
    find-changed-files:
        runs-on: "ubuntu-latest"
        outputs:
            is_yaml_changed: "${{ steps.filter.outputs.yaml }}"
            is_markdown_changed: "${{ steps.filter.outputs.markdown }}"
            is_json_changed: "${{ steps.filter.outputs.json }}"
            changed_or_added_files: "${{ steps.filter.outputs.changed-or-added-files }}"
            changed_or_added_files_list: "${{ steps.filter.outputs.changed-or-added-files_files }}"
        permissions:
            pull-requests: "read"
        steps:
            - name: "Checkout ${{ github.event.repository.name }}"
              uses: "actions/checkout@v4"
              with:
                  fetch-depth: 1

            - name: "Find changed files"
              uses: "dorny/paths-filter@v3"
              id: "filter"
              with:
                  list-files: "shell"

                  filters: |
                      yaml:
                      - "**/*.yaml"
                      - "**/*.yml"
                      markdown:
                      - "**/*.md"
                      json:
                      - "**/*.json"
                      changed-or-added-files:
                      - added|modified: '**'

    validate-yaml-changes:
        runs-on: "ubuntu-latest"
        needs: "find-changed-files"
        if: "${{ needs.find-changed-files.outputs.is_yaml_changed == 'true' }}"

        # NOTE: validating YAML changes takes around 1 minute.
        # If this job takes more than 5 minutes, it means that something is wrong.
        timeout-minutes: 5
        steps:
            - name: "Checkout ${{ github.event.repository.name }}"
              uses: "actions/checkout@v4"

            - name: "Login to Docker registry"
              uses: "docker/login-action@v3"
              with:
                  registry: "${{ env.REGISTRY }}"
                  username: "${{ github.actor }}"
                  password: "${{ secrets.GITHUB_TOKEN }}"

            - name: "Run YAML linter"
              run: "docker run --rm -v ${{ github.workspace }}:/linter_workdir/repo
                    ${{ env.REGISTRY }}/articola-tools/yaml-linter:latest"

    validate-markdown-changes:
        runs-on: "ubuntu-latest"
        needs: "find-changed-files"
        if: "${{ needs.find-changed-files.outputs.is_markdown_changed == 'true' }}"

        # NOTE: validating Markdown changes takes around 1 minute.
        # If this job takes more than 5 minutes, it means that something is wrong.
        timeout-minutes: 5
        steps:
            - name: "Checkout ${{ github.event.repository.name }}"
              uses: "actions/checkout@v4"

            - name: "Login to Docker registry"
              uses: "docker/login-action@v3"
              with:
                  registry: "${{ env.REGISTRY }}"
                  username: "${{ github.actor }}"
                  password: "${{ secrets.GITHUB_TOKEN }}"

            - name: "Run Dockerfile linter"
              run: "docker run --rm -v ${{ github.workspace }}:/linter_workdir/repo
                    ${{ env.REGISTRY }}/articola-tools/markdown-linter:latest"

    validate-json-changes:
        runs-on: "ubuntu-latest"
        needs: "find-changed-files"
        if: "${{ needs.find-changed-files.outputs.is_json_changed == 'true' }}"

        # NOTE: validating JSON changes takes around 1 minute.
        # If this job takes more than 5 minutes, it means that something is wrong.
        timeout-minutes: 5
        steps:
            - name: "Checkout ${{ github.event.repository.name }}"
              uses: "actions/checkout@v4"

            - name: "Login to Docker registry"
              uses: "docker/login-action@v3"
              with:
                  registry: "${{ env.REGISTRY }}"
                  username: "${{ github.actor }}"
                  password: "${{ secrets.GITHUB_TOKEN }}"

            - name: "Run Dockerfile linter"
              run: "docker run --rm -v ${{ github.workspace }}:/linter_workdir/repo
                    ${{ env.REGISTRY }}/articola-tools/json-linter:latest --check"

    validate-file-paths:
        runs-on: "ubuntu-latest"
        needs: "find-changed-files"
        if: "${{ needs.find-changed-files.outputs.changed_or_added_files == 'true' }}"

        # NOTE: validating file paths takes around 1 minute.
        # If this job takes more than 5 minutes, it means that something is wrong.
        timeout-minutes: 5
        steps:
            - name: "Validate file paths"
              run: |
                  for path in ${{ needs.find-changed-files.outputs.changed_or_added_files_list }}; do

                  # NOTE: ignore `.idea` folder because it's generated. Ignore files with special names.

                  if [[ "$path" != .idea* && "$path" != *Dockerfile && "$path" != *README.md && "$path" != *LICENSE ]]; then
                  docker run --rm ${{ env.REGISTRY }}/articola-tools/file-path-validator \
                  --naming-convention snake_case --path-to-validate "$path";
                  fi
                  done